### ISSUE TITLE
What are the keys in dataloader for fashionIQ and fashionGen dataset?

### ISSUE THREAD

**Issue by hmd78** [BrandonHanx/FAME-ViL#6]
## ❓ Questions and Help
Hi,
Thank you for your work,
I wonder what are the missing keys for fashionIQ dataset?
the original dataset doesn't have 'fake_data' , 'target_id' and 'garment_class' values.
Also for fashionGen dataset and dataloader as it is implemented in "mmf/datasets/builders/fashionall/database.py' , the original dataset keys (h5 file) doesn't contain these keys ("image_path", "id", "sentences", "attributes_id", etc).
I can't evaluate and reproduce results without these .
Is there any script for preparing datasets or 
something like that?

**Comment by BrandonHanx** [comment]
Please use the pre-processed data here https://github.com/BrandonHanx/mmf#data-preparation
